# Device Name
device_name: "DIGIT"
# Pixel Per Millimeter
ppmm: 0.0405
# Desired Image Width and Height
imgh: 240
imgw: 320
# Raw image width, height, and framerate
raw_imgh: 240 
raw_imgw: 320
framerate: 30